name: hello world

on: push

jobs:
  hello:
    runs-on: [self-hosted, default]
    steps:
    - run: echo 'hello world'

  hello-docker:
    runs-on: self-hosted
    container:
      image: lampepfl/dotty:2020-11-19
    steps:
    - run: echo 'hello docker'
